---
- hosts: localhost
  connection: local 
  
  tasks:
    - name: Create or update Keycloak client (minimal example), authentication with credentials
      community.general.keycloak_client:
        auth_keycloak_url: https://domain.org
        auth_realm: SSO-test
        auth_username: admin
        auth_password: password
        realm: SSO-test
        client_id: test-test
        description: "Это тестовый клиент"
        standard_flow_enabled: true
        implicit_flow_enabled: false
        direct_access_grants_enabled: false
        service_accounts_enabled: false
        authorization_services_enabled: false
        public_client: false        
 
        root_url: http://localhost/
        admin_url: https://localhost/
        web_origins:
          - http://localhost/*
        redirect_uris:
          - https://www.example.com/*
          - http://localhost/*  
        base_url: /
        enabled: true
        frontchannel_logout: true
        state: present



    # - name: Create a new client
    #   community.general.keycloak_client:
    #     auth_keycloak_url: https://domain.org
    #     auth_realm: SSO-test
    #     auth_client_id: admin-cli
    #     auth_username: admin
    #     auth_password: password
    #     state: present
    #     realm: SSO-test
    #     client_id: test-new
    #     id: d8b127a3-31f6-44c8-a7e4-4ab9a3e78d95
    #     name: this_is_a_test
    #     description: Description of this wonderful client
    #     root_url: https://www.example.com/
    #     admin_url: https://www.example.com/admin_url
    #     base_url: basepath
    #     enabled: true
    #     client_authenticator_type: client-secret
    #     secret: REALLYWELLKEPTSECRET
    #     redirect_uris:
    #       - https://www.example.com/*
    #       - http://localhost:8888/
    #     web_origins:
    #       - https://www.example.com/*
    #     not_before: 1507825725
    #     bearer_only: false
    #     consent_required: false
    #     standard_flow_enabled: true
    #     implicit_flow_enabled: false
    #     direct_access_grants_enabled: false
    #     service_accounts_enabled: false
    #     authorization_services_enabled: false
    #     public_client: false
    #     frontchannel_logout: false
    #     protocol: openid-connect
    #     full_scope_allowed: false
    #     default_roles:
    #       - test01
    #       - test02
    #     authentication_flow_binding_overrides:
    #         browser: 4c90336b-bf1d-4b87-916d-3677ba4e5fbb
    #     protocol_mappers:
    #       - config:
    #            access.token.claim: true
    #            claim.name: "family_name"
    #            id.token.claim: true
    #            jsonType.label: String
    #            user.attribute: lastName
    #            userinfo.token.claim: true
    #          consentRequired: true
    #          consentText: "${familyName}"
    #          name: family name
    #          protocol: openid-connect
    #          protocolMapper: oidc-usermodel-property-mapper
    #        - config:
    #            attribute.name: Role
    #            attribute.nameformat: Basic
    #            single: false
    #          consentRequired: false
    #          name: role list
    #          protocol: saml
    #          protocolMapper: saml-role-list-mapper
    #     attributes:
    #       # saml.authnstatement: true
    #       # saml.client.signature: true
    #       # saml.force.post.binding: true
    #       # saml.server.signature: true
    #       # saml.signature.algorithm: RSA_SHA256
    #       # saml.signing.certificate: CERTIFICATEHERE
    #       # saml.signing.private.key: PRIVATEKEYHERE
    #       # saml_force_name_id_format: false
    #       # saml_name_id_format: username
    #       # saml_signature_canonicalization_method: "http://www.w3.org/2001/10/xml-exc-c14n#"
    #       user.info.response.signature.alg: RS256
    #       request.object.signature.alg: RS256
    #       use.jwks.url: true
    #       jwks.url: JWKS_URL_FOR_CLIENT_AUTH_JWT
    #       jwt.credential.certificate: JWT_CREDENTIAL_CERTIFICATE_FOR_CLIENT_AUTH
